conformant = "Pass"
output = """
aliases_newtype.py:11: error: Argument 1 to "UserId" has incompatible type "str"; expected "int"  [arg-type]
aliases_newtype.py:12: error: Incompatible types in assignment (expression has type "int", variable has type "UserId")  [assignment]
aliases_newtype.py:20: error: Cannot use isinstance() with NewType type  [misc]
aliases_newtype.py:23: error: Cannot subclass "NewType"  [misc]
aliases_newtype.py:32: error: String argument 1 "BadName" to NewType(...) does not match variable name "GoodName"  [misc]
aliases_newtype.py:38: error: "GoodNewType1" expects no type arguments, but 1 given  [type-arg]
aliases_newtype.py:41: error: Cannot redefine "GoodNewType2" as a NewType  [misc]
aliases_newtype.py:41: error: Name "GoodNewType2" already defined on line 36  [no-redef]
aliases_newtype.py:44: error: Argument 2 to NewType(...) must be subclassable (got "int | str")  [valid-newtype]
aliases_newtype.py:47: error: Type variable "aliases_newtype.T" is unbound  [valid-type]
aliases_newtype.py:47: note: (Hint: Use "Generic[T]" or "Protocol[T]" base class to bind "T" inside a class)
aliases_newtype.py:47: note: (Hint: Use "T" in function signature to bind "T" inside a function)
aliases_newtype.py:49: error: NewType cannot be used with protocol classes  [misc]
aliases_newtype.py:51: error: Argument 2 to NewType(...) must be subclassable (got "Literal[7]")  [valid-newtype]
aliases_newtype.py:58: error: Argument 2 to NewType(...) must be subclassable (got "TD1")  [valid-newtype]
aliases_newtype.py:60: error: NewType(...) expects exactly two positional arguments  [misc]
aliases_newtype.py:62: error: Argument 2 to NewType(...) must be subclassable (got "Any")  [valid-newtype]
"""
conformance_automated = "Fail"
errors_diff = """
Line 11: Unexpected errors ['aliases_newtype.py:11: error: Argument 1 to "UserId" has incompatible type "str"; expected "int"  [arg-type]']
Line 12: Unexpected errors ['aliases_newtype.py:12: error: Incompatible types in assignment (expression has type "int", variable has type "UserId")  [assignment]']
Line 20: Unexpected errors ['aliases_newtype.py:20: error: Cannot use isinstance() with NewType type  [misc]']
Line 23: Unexpected errors ['aliases_newtype.py:23: error: Cannot subclass "NewType"  [misc]']
Line 32: Unexpected errors ['aliases_newtype.py:32: error: String argument 1 "BadName" to NewType(...) does not match variable name "GoodName"  [misc]']
Line 38: Unexpected errors ['aliases_newtype.py:38: error: "GoodNewType1" expects no type arguments, but 1 given  [type-arg]']
Line 41: Unexpected errors ['aliases_newtype.py:41: error: Cannot redefine "GoodNewType2" as a NewType  [misc]', 'aliases_newtype.py:41: error: Name "GoodNewType2" already defined on line 36  [no-redef]']
Line 44: Unexpected errors ['aliases_newtype.py:44: error: Argument 2 to NewType(...) must be subclassable (got "int | str")  [valid-newtype]']
Line 47: Unexpected errors ['aliases_newtype.py:47: error: Type variable "aliases_newtype.T" is unbound  [valid-type]']
Line 49: Unexpected errors ['aliases_newtype.py:49: error: NewType cannot be used with protocol classes  [misc]']
Line 51: Unexpected errors ['aliases_newtype.py:51: error: Argument 2 to NewType(...) must be subclassable (got "Literal[7]")  [valid-newtype]']
Line 58: Unexpected errors ['aliases_newtype.py:58: error: Argument 2 to NewType(...) must be subclassable (got "TD1")  [valid-newtype]']
Line 60: Unexpected errors ['aliases_newtype.py:60: error: NewType(...) expects exactly two positional arguments  [misc]']
Line 62: Unexpected errors ['aliases_newtype.py:62: error: Argument 2 to NewType(...) must be subclassable (got "Any")  [valid-newtype]']
"""
