conformant = "Pass"
output = """
namedtuples_type_compat.py:22: error: Incompatible types in assignment (expression has type "Point", variable has type "tuple[int, int]")  [assignment]
namedtuples_type_compat.py:23: error: Incompatible types in assignment (expression has type "Point", variable has type "tuple[int, str, str]")  [assignment]
"""
conformance_automated = "Fail"
errors_diff = """
Line 22: Unexpected errors ['namedtuples_type_compat.py:22: error: Incompatible types in assignment (expression has type "Point", variable has type "tuple[int, int]")  [assignment]']
Line 23: Unexpected errors ['namedtuples_type_compat.py:23: error: Incompatible types in assignment (expression has type "Point", variable has type "tuple[int, str, str]")  [assignment]']
"""
